[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ansibase"
version = "1.0.1"
description = "Inventaire Ansible dynamique avec PostgreSQL"
readme = "README.md"
license = "GPL-3.0"
requires-python = ">=3.10"
authors = [{ name = "mbecode" }]
keywords = ["ansible", "inventory", "postgresql", "dynamic-inventory"]
classifiers = [
    # How mature is this project? Common values are
    "Development Status :: 4 - Beta",

    # Indicate who your project is intended for
    "Intended Audience :: System Administrators",
    "Topic :: System :: Systems Administration",

    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "SQLAlchemy>=2.0,<3.0",
    "psycopg2-binary>=2.9,<3.0",
    "pyyaml>=6.0",
    "alembic>=1.12,<2.0",
]

[project.optional-dependencies]
ansible = ["ansible-core>=2.15"]

[project.scripts]
ansibase-inventory = "ansibase.ansible.inventory:main"
ansibase-db = "ansibase.cli:main"

[project.urls]
Homepage = "https://github.com/MbeHenri/ansibase.git"
Repository = "https://github.com/MbeHenri/ansibase.git"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ansibase = ["migrations/*.py", "migrations/*.mako", "migrations/versions/*.py"]
