name: Deploy package and other

on:
  # üöÄ Ne d√©clenche ce workflow que sur les push vers la branche "main"
  push:
    branches:
      - master
env:
  PIP_ACCESS_TOKEN: ${{ secrets.PIP_ACCESS_TOKEN }}

jobs:
  check-diff:
    # Ce job v√©rifie les fichiers modifi√©s pour d√©terminer quels pipelines poursuivre par la suite
    runs-on: ubuntu-latest
    outputs:
      deploy_package: ${{ steps.filter.outputs.package || 'false' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Valeurs par d√©faut pour les ex√©cutions manuelles (ou autres √©v√©nements)
      - name: Check changed files
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        id: filter
        uses: dorny/paths-filter@v3 # Plugin pour d√©tecter quels fichiers ont √©t√© modifi√©s
        with:
          filters: |
            package:
              - 'packages/**'     # Surveille le dossier de l'api

  deploy-package:
    needs: [check-diff] # Attend la sortie du job "check-diff"
    if: |
      github.event_name == 'push' && needs.check-diff.outputs.deploy_package == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Sp√©cifie la version de Python √† utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build packages/ansibase

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIP_ACCESS_TOKEN }}
        run: |
          twine upload packages/ansibase/dist/* --repository pypi
